sudo: required
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  chrome: stable
node_js:
  - "8.11.3"
before_script:
  - ls -l /opt/google/chrome/chrome-sandbox
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - ls -l /opt/google/chrome/chrome-sandbox
  - npm i -g npm@6.4.0
  - npm install -g mocha
